steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/doodlex/frontend:latest'
      - '-f'
      - 'docker/Dockerfile.frontend'
      - '--build-arg'
      - 'NEXT_PUBLIC_BACKEND_URL=https://doodlex-backend-545432289507.asia-south1.run.app/api/v1'
      - '--build-arg'
      - 'NEXT_PUBLIC_WS_URL=wss://doodlex-ws-545432289507.asia-south1.run.app'
      - '--build-arg'
      - 'GOOGLE_API_KEY=PLACEHOLDER'
      - '.'
images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/doodlex/frontend:latest'
options:
  machineType: 'E2_HIGHCPU_8'
timeout: 1800s
