# renew_before_expiry = 30 days
version = 3.3.0
archive_dir = /etc/letsencrypt/archive/doodlex.vinayaknagar.tech
cert = /etc/letsencrypt/live/doodlex.vinayaknagar.tech/cert.pem
privkey = /etc/letsencrypt/live/doodlex.vinayaknagar.tech/privkey.pem
chain = /etc/letsencrypt/live/doodlex.vinayaknagar.tech/chain.pem
fullchain = /etc/letsencrypt/live/doodlex.vinayaknagar.tech/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = d710b874f04ac2fe8c03cecea48e5e54
rsa_key_size = 4096
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
doodlex.vinayaknagar.tech = /var/www/certbot
