FROM node:22-alpine

WORKDIR /usr/src/app

ARG DATABASE_URL

COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/web ./apps/web

RUN npm install -g pnpm
RUN pnpm install
RUN cd apps/web && pnpm install
RUN pnpm --filter @repo/db run db:generate
RUN DATABASE_URL=${DATABASE_URL} pnpm run build:all

EXPOSE 3000

CMD ["pnpm","run","start:web"]