FROM node:22-alpine

WORKDIR /usr/src/app

RUN apk add --no-cache python3 make g++ gcc postgresql-client

COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/http-server ./apps/http-server

RUN npm install -g pnpm
RUN pnpm install
RUN pnpm run db:generate

RUN cd apps/http-server && rm -f tsconfig.tsbuildinfo && pnpm run build

# Add an entrypoint script
COPY docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 3001

# Use the entrypoint script to run migrations before starting the service
ENTRYPOINT ["/entrypoint.sh"]