FROM node:22-alpine

WORKDIR /usr/src/app

ARG DATABASE_URL
ARG GOOGLE_API_KEY
ENV GOOGLE_API_KEY=$GOOGLE_API_KEY

RUN apk add --no-cache python3 make g++ gcc

COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/web ./apps/web

RUN npm install -g pnpm
RUN pnpm install
RUN pnpm run db:generate
RUN DATABASE_URL=${DATABASE_URL} pnpm run build

EXPOSE 3000

CMD ["pnpm","run","start:web"]


