name: Deploy DoodleX to DigitalOcean
on: 
    push:
        branches:
            - deployment
    workflow_dispatch: 
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
              with: 
                fetch-depth: 0
            
            - name: Install SSH Key
              uses: shimataro/ssh-key-action@v2
              with: 
                key: ${{secrets.SSH_PRIVATE_KEY}}
                known_hosts: ${{secrets.SSH_KNOWN_HOSTS}}
                if_key_exists: replace

            - name: Deploy to DigitalOcean
              run: |
                ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "cd /opt/doodlex && bash deploy.sh"